export default {
  title: "I Meetup PyData Pará",
  subtitle: "Primeira edição no Pará",
  date: "Sábado, 06/09/2025",
  time: "9h às 18h",
  location: "Local a definir",
  attendees: "60-100 pessoas",
  status: "upcoming",
  subscribe: "",
  keynotes: [
    {
      name: "Dr. Ana Rodrigues",
      title: "Pesquisadora em IA",
      company: "Universidade Federal do Pará",
      talk: "O Futuro da IA no Brasil",
      time: "10:00 - 10:45",
      photo: "/placeholder.svg?height=200&width=300&text=Dr.+Ana+Rodrigues",
      linkedin: "https://linkedin.com/in/ana-rodrigues",
      instagram: "https://instagram.com/ana_rodrigues_ai",
      twitter: "https://twitter.com/ana_rodrigues_ai",
    },
    {
      name: "Prof. Carlos Lima",
      title: "Especialista em Ética Digital",
      company: "Instituto de Tecnologia",
      talk: "Ética em IA",
      time: "16:30 - 17:15",
      photo: "/placeholder.svg?height=200&width=300&text=Prof.+Carlos+Lima",
      linkedin: "https://linkedin.com/in/carlos-lima",
      instagram: "https://instagram.com/carlos_lima_ethics",
      twitter: "https://twitter.com/carlos_lima_ethics",
    },
  ],
  speakers: [
    {
      name: "Ana Silva",
      title: "Data Scientist",
      company: "Tech Corp",
      talk: "Análise de Dados com Pandas",
      time: "11:00 - 11:40",
      photo: "/placeholder.svg?height=150&width=150&text=Ana+Silva",
      linkedin: "https://linkedin.com/in/ana-silva",
      instagram: "https://instagram.com/ana_silva_data",
      twitter: "https://twitter.com/ana_silva_data",
    },
    {
      name: "Carlos Santos",
      title: "ML Engineer",
      company: "AI Solutions",
      talk: "Machine Learning na Prática",
      time: "11:40 - 12:20",
      photo: "/placeholder.svg?height=150&width=150&text=Carlos+Santos",
      linkedin: "https://linkedin.com/in/carlos-santos",
      instagram: "https://instagram.com/carlos_ml",
      twitter: "https://twitter.com/carlos_ml",
    },
    {
      name: "Maria Oliveira",
      title: "Data Visualization Expert",
      company: "VizTech",
      talk: "Visualização de Dados com Matplotlib",
      time: "13:30 - 14:10",
      photo: "/placeholder.svg?height=150&width=150&text=Maria+Oliveira",
      linkedin: "https://linkedin.com/in/maria-oliveira",
      instagram: "https://instagram.com/maria_viz",
      twitter: "https://twitter.com/maria_viz",
    },
    {
      name: "João Pereira",
      title: "Deep Learning Researcher",
      company: "AI Lab",
      talk: "Deep Learning com TensorFlow",
      time: "14:10 - 14:50",
      photo: "/placeholder.svg?height=150&width=150&text=João+Pereira",
      linkedin: "https://linkedin.com/in/joao-pereira",
      instagram: "https://instagram.com/joao_dl",
      twitter: "https://twitter.com/joao_dl",
    },
    {
      name: "Fernanda Costa",
      title: "NLP Specialist",
      company: "Language AI",
      talk: "Processamento de Linguagem Natural",
      time: "15:10 - 15:50",
      photo: "/placeholder.svg?height=150&width=150&text=Fernanda+Costa",
      linkedin: "https://linkedin.com/in/fernanda-costa",
      instagram: "https://instagram.com/fernanda_nlp",
      twitter: "https://twitter.com/fernanda_nlp",
    },
  ],
  sponsors: {
    gold: [
      {
        name: "Empresa Gold 1",
        logo: "/placeholder.svg?height=80&width=200&text=Gold+Sponsor+1",
        website: "https://empresa-gold-1.com",
      },
      {
        name: "Empresa Gold 2",
        logo: "/placeholder.svg?height=80&width=200&text=Gold+Sponsor+2",
        website: "https://empresa-gold-2.com",
      },
    ],
    silver: [
      {
        name: "Empresa Prata 1",
        logo: "/placeholder.svg?height=60&width=150&text=Silver+1",
        website: "https://empresa-prata-1.com",
      },
      {
        name: "Empresa Prata 2",
        logo: "/placeholder.svg?height=60&width=150&text=Silver+2",
        website: "https://empresa-prata-2.com",
      },
      {
        name: "Empresa Prata 3",
        logo: "/placeholder.svg?height=60&width=150&text=Silver+3",
        website: "https://empresa-prata-3.com",
      },
    ],
    bronze: [
      {
        name: "Empresa Bronze 1",
        logo: "/placeholder.svg?height=50&width=120&text=Bronze+1",
        website: "https://empresa-bronze-1.com",
      },
      {
        name: "Empresa Bronze 2",
        logo: "/placeholder.svg?height=50&width=120&text=Bronze+2",
        website: "https://empresa-bronze-2.com",
      },
      {
        name: "Empresa Bronze 3",
        logo: "/placeholder.svg?height=50&width=120&text=Bronze+3",
        website: "https://empresa-bronze-3.com",
      },
      {
        name: "Empresa Bronze 4",
        logo: "/placeholder.svg?height=50&width=120&text=Bronze+4",
        website: "https://empresa-bronze-4.com",
      },
    ],
    discounts: [
      {
        name: "Desconto Estudantil",
        logo: "/placeholder.svg?height=40&width=100&text=Desconto+Estudantil",
        website: "https://www.alura.com.br",
      },
    ],
    community: [
      {
        name: "Python Pará",
        logo: "/placeholder.svg?height=40&width=100&text=Python+PA",
        website: "https://python-para.org",
      },
      {
        name: "Data Science PA",
        logo: "/placeholder.svg?height=40&width=100&text=DS+PA",
        website: "https://datasciencepa.org",
      },
      {
        name: "AI Belém",
        logo: "/placeholder.svg?height=40&width=100&text=AI+Belém",
        website: "https://ai-belem.org",
      },
      {
        name: "Tech Amazônia",
        logo: "/placeholder.svg?height=40&width=100&text=Tech+AM",
        website: "https://tech-amazonia.org",
      },
    ],
  },
  photos: [
    {
      src: "/placeholder.svg?height=300&width=400&text=Evento+Python+Belém",
      alt: "Evento Python Belém",
      caption: "Meetup Python Belém 2024",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Workshop+Data+Science",
      alt: "Workshop Data Science",
      caption: "Workshop de Data Science",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Palestra+IA",
      alt: "Palestra sobre IA",
      caption: "Palestra sobre IA na Amazônia",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Networking+Tech",
      alt: "Networking Tech",
      caption: "Networking da comunidade tech",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Hackathon+PA",
      alt: "Hackathon Pará",
      caption: "Hackathon Pará 2024",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Comunidade+Diversa",
      alt: "Comunidade Diversa",
      caption: "Diversidade na tecnologia",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Apresentação+ML",
      alt: "Apresentação Machine Learning",
      caption: "Apresentação sobre ML",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Grupo+Estudo",
      alt: "Grupo de Estudos",
      caption: "Grupo de estudos Python",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Tech+Talk",
      alt: "Tech Talk",
      caption: "Tech Talk na universidade",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Coding+Dojo",
      alt: "Coding Dojo",
      caption: "Coding Dojo da comunidade",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Palestra+Dados",
      alt: "Palestra sobre Dados",
      caption: "Análise de dados na prática",
    },
    {
      src: "/placeholder.svg?height=300&width=400&text=Evento+Inclusão",
      alt: "Evento Inclusão",
      caption: "Inclusão digital no Pará",
    },
  ],
};
